name: run-tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  # This job runs unit tests on a variety of OS and compiler combinations.
  test:
    name: Dub Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        compiler: [dmd-2.099.1, dmd-latest, ldc-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install D Compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.compiler }}

      - name: Run Tests
        run: dub -q test
  
  # Job for checking each example to ensure it's valid.
  check-examples:
    name: Validate Examples
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        compiler: [dmd-2.099.1, dmd-latest, ldc-latest]
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install D Compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.compiler }}
      
      - name: Validate basic-usage
        working-directory: examples/basic-usage
        run: dub -q run
      
      - name: Validate custom-provider
        working-directory: examples/custom-provider
        run: dub -q test
